// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Simple_Signature
{

    public class Signatures
    {

        [JsonProperty("_id")]
        public string Id { get; set; }

        [JsonProperty("createdAt")]
        public DateTime CreatedAt { get; set; }

        [JsonProperty("firm")]
        public string Firm { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("value")]
        public string Value { get; set; }

        [JsonProperty("img")]
        public string Image { get; set; }

        static public Signatures getDefaultInterne(Signatures[] campaigns)
        {
            foreach (var item in campaigns)
            {
                if(item.Name == "interne default")
                {
                    return item;
                }
            }
            return null;
        }

        static public Signatures getDefaultExterne(Signatures[] campaigns)
        {
            foreach (var item in campaigns)
            {
                if (item.Name == "externe default")
                {
                    return item;
                }
            }
            return null;
        }
    }

}

